[package]
name = "Final"
version = "0.1.0"
edition = "2021"


[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
plotters = {version = "0.3", features = ["evcxr"]} 
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
